name: Auto Build Dist - API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build on VPS
      uses: appleboy/ssh-action@v1
      with:
        host: 72.61.119.52
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/apps/jobsy-api
          bash -l deploy.sh
